type Query {
  properties: [Property]
  propertyById(id: ID): Property
  rates: [Rate]
  ratesByRatePlanCode(ratePlanCode: String): Rate
  reviews: [Review]
  reviewsByPropertyCode(propertyCode: String): [Review]
  user: User
  profile(userName: String): Profile
}

type User {
  name: String
  profile: String
}

type Profile {
  email: String
  userName: String
  name: String
  accounts: [Account]
}

type Account {
  profileImage: String
  name: String
}
